site_name: voilern's Notebook
site_url: https://voilern.github.io/Note/
site_author: voilern
site_description: voilern's Notebook
repo_url: https://github.com/voilern/Note/
repo_name: voilern/Note
copyright: Copyright &copy; 2025 voilern

theme:
  name: material
  language: zh
  text: LXGW WenKai Screen
  code: CodeNewRoman Nerd Font Mono

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  features:
    - navigation.indexes
    - navigation.tracking       #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs           #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.top
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/voilern
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/403057961
    - icon: fontawesome/solid/envelope
      link: mailto:<hejiayi@zju.edu.cn>

extra_css:
  - stylesheets/css/card.css
  - stylesheets/css/flink.css
  - stylesheets/css/extra.css
  # - stylesheets/css/rounded_corner.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://static.zeoseven.com/zsft/292/main/result.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


plugins:
  - search

nav:
  - Home: index.md
  - Computer Science:
    - 数据结构基础: 
      - ComputerScience/FDS/index.md
    - 面向对象程序设计:  
      - ComputerScience/OOP/index.md
    - 高级数据结构与算法分析:
      - ComputerScience/ADS/index.md
      - ComputerScience/ADS/Lec01.md
      - ComputerScience/ADS/Lec02.md
      - ComputerScience/ADS/Lec03.md
      - ComputerScience/ADS/Lec04.md
      - ComputerScience/ADS/Lec05.md
      - ComputerScience/ADS/Lec06.md
      - ComputerScience/ADS/Lec07.md
      - ComputerScience/ADS/Lec08.md
      - ComputerScience/ADS/Lec09.md
      - ComputerScience/ADS/Lec10.md
      - ComputerScience/ADS/Lec11.md
      - ComputerScience/ADS/Lec12.md
      - ComputerScience/ADS/Lec13.md
      - ComputerScience/ADS/Lec14.md
      - ComputerScience/ADS/Lec15.md
      - ComputerScience/ADS/Ex01.md
    - CS106L:
      - ComputerScience/CS106L/index.md
      - ComputerScience/CS106L/lec1.md
      - ComputerScience/CS106L/lec2.md
  # - Others: Others/index.md